name: Build and Push

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  call-shared-workflow:
    uses: autoshop-crm/.github/.github/workflows/shared-build.yml@main
    with:
      image_name: autoshop-crm/autoshop-web-spec
      dockerfile: Dockerfile
      context: .
      push_latest: true
